name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright Browsers
        run: |
          python -m playwright install
          python -m playwright install-deps

      - name: Run Pytest
        run: |
          pytest --html=report.html --self-contained-html

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report
          path: report.html

      - name: Upload Playwright Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: playwright-report/
          if-no-files-found: ignore
