name: Playwright Tests

on:
  push:
    branches: 
      - '**'
  pull_request:
  workflow_dispatch:
  create:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright Browsers
        run: |
          python -m playwright install
          python -m playwright install-deps

      - name: Run Pytest
        run: |
          pytest --html=report.html --self-contained-html

      - name: Upload HTML Report
        id: upload-report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report
          path: report.html

      - name: Upload Playwright Test Artifacts
        id: upload-playwright-artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: playwright-report/
          if-no-files-found: ignore
        
      - name: Send Email Notification
        if: always()
        run: |
          python scripts/send_email.py \
            "${{ job.status }}" \
            "${{ github.repository }}" \
            "${{ github.workflow }}" \
            "${{ steps.upload-report.outputs.artifact-url }}"
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_SMTP_SERVER: ${{ secrets.EMAIL_SMTP_SERVER }}
          EMAIL_SMTP_PORT: ${{ secrets.EMAIL_SMTP_PORT }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
